# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-07 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comments_approved_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='data_published',
        ),
        migrations.AddField(
            model_name='comments',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 12, 5, 34, 170802, tzinfo=utc)),
        ),
    ]
